// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include <Commands/ElevatorDown.h>

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

ElevatorDown::ElevatorDown(double speed) : mSpeed(speed) {

	Requires(Robot::elevator.get());
}

// Called just before this Command runs the first time
void ElevatorDown::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void ElevatorDown::Execute() {
	Elevator::getInstance()->SetElevator(mSpeed);
}

// Make this return true when this Command no longer needs to run execute()
bool ElevatorDown::IsFinished() {
    return Elevator::getInstance()->IsRevLimitSwitchClosed();
}

// Called once after isFinished returns true
void ElevatorDown::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ElevatorDown::Interrupted() {

}
