// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef OI_H
#define OI_H

#include "WPILib.h"

class OI {
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static std::shared_ptr<OI> self;
	std::shared_ptr<frc::Joystick> driver;
	frc::JoystickButton dA;
	frc::JoystickButton dB;
	frc::JoystickButton dX;
	frc::JoystickButton dY;
	frc::JoystickButton dLB;
	frc::JoystickButton dRB;

	std::shared_ptr<frc::Joystick> coDriver;
	frc::JoystickButton coA;
	frc::JoystickButton coB;
	frc::JoystickButton coX;
	frc::JoystickButton coY;
	frc::JoystickButton coLB;
	frc::JoystickButton coRB;
	frc::JoystickButton coStart;
	frc::JoystickButton coSelect;

public:
	OI();

	static std::shared_ptr<OI> getInstance;

	std::shared_ptr<frc::Joystick> getdriver();
	std::shared_ptr<frc::Joystick> getcoDriver();


	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
};

#endif
