#ifndef ROBOTMAP_H
#define ROBOTMAP_H

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "WPILib.h"
#include "ctre/Phoenix.h"

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around
 */
class RobotMap {
	void init();
public:

//..........Motors..........

  //..........Chassis..........
	  static const int kIDRight1Wheel = 2;
	  static const int kIDLeft1Wheel = 1;
	  static const int kIDRight2Wheel = 4;
	  static const int kIDLeft2Wheel = 3;
	//..........Intake..........
	  static const int kIDIntakeMotor = 5;
	//..........Arm..........
	  static const int kIDArmMotor = 6;
	  static const int kIDArmPot = 3;
	//.........Elevator.........
	  static const int kIDTopElevator = 7;
	  static const int kIDBottomElevator = 7;

	//........Climber.............
	  static const int kIDRightClimber = 10;
	  static const int kIDLeftClimber =10;
	  static const int kIDClimberForward = 10;
	  static const int kIDClimberReverse = 10;

	//.......Claw.......
	  static const int kIDClawForward = 3;
	  static const int kIDClawReverse = 3;


//..........Solenoids..........

};

static const int kPID_PrimaryClosedLoop = 0;
static const int kPID_CascadedClosedLoop = 1;

static const int kTimeout_10Millis = 10;
static const int kTimeout_DontBlock = 0;

#endif
